export const JWT_SECRET = process.env.JWT_SECRET || 'Super-secret-key.123'
export const IS_PRODUCTION = process.env.NODE_ENV === 'production'

export const TRANSCRIBE_EDIT_PROMPT = `Men senga matn beraman. Matnni to'g'irlashing kerak ushbu narsalarni rioya qilgan holda:\n- Matndagi tinish belgilari to’g’irlanishi kerak. Masalan: “mana bu qur'on bizga ana shu sun'atlarni o'rgatadi qoidalarni o'rgatadi hayot nima ekanligini bildiradi”, quydagi tarzda to’g’irlanishi kerak: “mana bu qur'on bizga ana shu sunnatlarni o'rgatadi. Qoidalarni o'rgatadi. Hayot nima ekanligini bildiradi.”\n- O'zbekcha so'zlar to'g'ri yozishing kerak. Masalan: "Ubay etdi", bu xato. To'g'ri yozilishi: "Ubay aytdi".\n- Javobing orasi boshqa birorta ham o'zingdan gap yozma, "Avvalo, keling, matnlarni birma-bir ko'rib chiqaylik", yoki: "Agar yana qandaydir savollaringiz yoki tuzatishlar bo'lsa, men doimo yordam berishga tayyorman", deb javob orasida umuman yozma. Shunchaki matnni yozib ber.\n\nMatn:\n`

export const EDIT_PROMPT = `Ushbu matnni o‘zbek tili grammatikasi: sintaksis va morfologiyasiga mos ravishda, qo‘yidagilarga rioya qilgan holda tahrir qilib bering:\n– Matnda arab tilida yozilgan iboralarni lotin harflari asosidagi o‘zbek alifbosida bexato yozing. Eslatma: o‘zbek alifbosida «w» harfi mavjud emas.\n– Matndagi ko‘chirma gaplarni qo‘shtirnoqlar bilan ajratib yozing.\n– Matnda keltirilgan voqea va hikoyalarni tushirib qoldirmasdan to‘liq yozing.\n– Matndagi imloviy xatolarni tuzating.\n– Jumlalar o‘rtasidagi mantiqiy ketmaketlikka rioya qiling.\n-Nihoiy matndagi har bir abzatzlarni ushbu HTML <p></p> tagi orasiga qo'yib yozib ber. <p>mana bu shaklda</p>\n\nMatn:\n`

export const CORRECTION_PROMPT =
	"Men senga o‘zbekcha matin beraman, unda quron oyatlari arabcha aralash va undagi tinish belgilarini quyasan yani nuqta, vergul kabi va suzlarda agarda xato bolsa 1 harfgacha uzgartirish kerak bulsa uzgartir bulmasa tegma. Arabcha va quron oyatlariga tegma. \n-Nihoiy matndagi har bir abzatzlarni ushbu HTML <p></p> tagi orasiga qo'yib yozib ber. <p>mana bu shaklda</p>\n\nMatn:\n"
